#!/bin/sh

RELEASE_DIR="OI-on-SD-`date +%Y%m%d`"
TMPDIR=`mktemp build-OI-on-SD.XXXX -d`

cd $TMPDIR
build-v3 keepfiles
mkinitramfs-v3
mkrootfs.ext2 nfsroot-v3-armel.tar


mkdir -p ../$RELEASE_DIR/openinkpot

mv initrd.gz rootfs.ext2 vmlinuz-2.6.25-v3-armel ../$RELEASE_DIR/openinkpot

cd ../$RELEASE_DIR
rm -rf ../$TMPDIR

echo '#!/bin/sh

insmod /mnt/openinkpot/reloaded.ko kernel=/mnt/openinkpot/vmlinuz-2.6.25-v3-armel initrd=/mnt/openinkpot/initrd.gz
' > openinkpot/boot-OI-V3.exe.txt

wget -O openinkpot/reloaded.ko http://openinkpot.org/pub/contrib/v3all-reloaded/reloaded.ko

tar cv openinkpot/ | gzip -9 > $RELEASE_DIR.tar.gz

pwd
